dist: focal

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

jdk: openjdk9

cache:
  directories:
    - $HOME/.cache/bazel
    - $HOME/.cache/apt

before_install:
  - echo "Installing C++ and Python"
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends --no-install-suggests g++ python-dev python3-dev python3-pip maven libnuma-dev libc-dev python3-venv  openmpi-bin libopenmpi-dev
  - sudo pip3 install cpplint
  - cp /var/cache/apt/archives/*.deb $HOME/.cache/apt/

jobs:
  include:
    - stage: "Build Stages"
      script:
        - ./build.sh -pyenv $(pwd)/ENV -bpath $(pwd)/build --cpp --release --test --style-check
      name: "Build CPP"
    - script:
        - python3 -m venv ENV
        - ./build.sh -pyenv $(pwd)/ENV -bpath $(pwd)/build --python --pytest
      name: "Build Python"
    - script:
        - ./build.sh -pyenv $(pwd)/ENV -bpath $(pwd)/build --java
      name: "Build Java"


