{% set version = '0.4.0'.lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cylon_version='.'.join(environ.get('CYLON_VERSION', '0.4.0').split('.')[:2]) %}

package:
  name: pygcylon
  version: {{ version }}

source:
  path: ../../..
#  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: pygcylon{{ cylon_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
  run_exports:
    - {{ pin_subpackage("gcylon", max_pin="x.x") }}

requirements:
  build:
    - cython>=0.29,<0.30
    - setuptools>=49.6.0
    - glog 0.4.0
    - cudf=21.08
    - cudatoolkit>=11.0
    - pyarrow=4.0.1
    - arrow-cpp=4.0.1
  run:
    - glog 0.4.0
    - cudf=21.08
    - cudatoolkit>=11.0
    - pyarrow=4.0.1
    - arrow-cpp=4.0.1

about:
  home: http://cylondata.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cylon C++ library
