name: Windows C++/Python - MSVC, MSMPI

on:
  push:
    branches:
      - main
      - 0.**
  pull_request:
    branches: 
      - main
      - 0.**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"  # You can specify a version or leave it as "latest"
          auto-update-conda: true
          activate-environment: cylon_dev
          environment-file: conda/environments/windows.yml

      - name: Activate conda
        run: conda activate cylon_dev
      - name: Build cylon, pycylon and run c++ tests
        run: python build.py --cpp --python --test
      - name: Run python tests
        run: python build.py --pytest
